name: Ticket data validation

on:
  workflow_dispatch:
  
jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Group of log lines
        run: |
          echo "***** Start Project Number Validation *****"
