name: Ticket data validation

on:
  workflow_dispatch:
  
jobs:
  project-number:
    runs-on: ubuntu-latest
    steps:
      - name: Checking the project number
        run: |
          echo "***** Start Project Number Validation *****"
          gcloud projects list --filter="project_number=901815459324"
          
          
          
